# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Merged Pull Requests to DDB

on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:

    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest
    env:
      ## Sets environment variable
      PR_NUMBER: ${{ github.event.pull_request }}   
      GITHUB_REPO: ${{ github.event.repo.url }}   

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 16  

      

    - name: Get changed files using defaults
      id: changed-files
      uses: tj-actions/changed-files@v19
      with:
        separator: ","    

    - run: npm i

    - run: |
        echo "Set from manual input: ${{ github.event.pull_request.number }}"
        echo "FOO=${{ github.event.pull_request.number }}" >> $GITHUB_ENV

    - run: npm run write 
      # with:
        # "github-url": ${{ github.event.repo.url }}
      #   modified-files: ${{ steps.changed-files.outputs.modified_files }}
      #   LOL: "hello"
      #   random: github.event.number
      #   TEST: github.event
      
    - run: echo github.event.number = ${{ github.event.number  }}
    - run: echo github.event.pull_request.number = ${{ github.event.pull_request.number }}
    - run: echo github.event.pull_request = ${{ github.event.pull_request }}
    - run: echo github.event.repo.url = ${{ github.event.repo.url }}

    - name: Get changed files using defaults
      run: echo The PR was merged
