# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Merged Pull Requests to DDB

on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:

    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 16  

    - name: Get changed files using defaults
      id: changed-files
      uses: tj-actions/changed-files@v19
      with:
        separator: ","    

    - run: npm i

    - run: npm run write 
      with:
        new-files: ${{ steps.changed-files.outputs.added_files }}
        modified-files: ${{ steps.changed-files.outputs.modified_files }}
      

    - name: Get changed files using defaults
      run: echo The PR was merged
